// Generated by CoffeeScript 1.6.2
(function() {
  window.languages = ["ru", "en"];

  window.translations = {
    ru: {
      home: "Главная",
      top: "Рейтинг",
      authors: "Авторы",
      search: "Поиск",
      elibrary: "eLibrary"
    },
    en: {
      home: "Home",
      top: "Top",
      authors: "Authors",
      search: "Search",
      elibrary: "eLibrary"
    }
  };

}).call(this);
