// Generated by CoffeeScript 1.6.2
(function() {
  window.languages = ["ru", "en"];

  window.translations = {
    ru: {
      choose_author_please: "Выберите пожалуйста автора",
      home: "Главная",
      top: "Рейтинг",
      authors: "Авторы",
      search: "Поиск",
      elibrary: "eLibrary",
      action_read: "Читать",
      actions: "Действия",
      adventures: "Приключения",
      all: "Все",
      author: "Автор",
      book_title: "Название",
      books: "Книги",
      detective: "Детектив",
      fantastic: "Фантастика",
      history: "Исторические",
      humor: "Юмор",
      lyrics: "Стихи/Лирика",
      section: "Раздел",
      sections: "Разделы"
    },
    en: {
      choose_author_please: "Выберите пожалуйста автора",
      home: "Home",
      top: "Top",
      authors: "Authors",
      search: "Search",
      elibrary: "eLibrary",
      action_read: "Read",
      actions: "Actions",
      adventures: "Adventures",
      all: "All",
      author: "Author",
      book_title: "Title",
      books: "Books",
      detective: "Detective",
      fantastic: "fantastic",
      history: "History",
      humor: "Humor",
      lyrics: "Lyrics",
      section: "Section",
      sections: "Sections"
    }
  };

}).call(this);
